# Generated by Django 5.1 on 2024-09-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('detail', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('youtube_Title', models.CharField(max_length=500)),
                ('youtube_link', models.URLField(blank=True)),
            ],
        ),
    ]
